spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/youzheng_web
    username: root
    password: dnwjd123
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: youzheng_web
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          batch_size: 100
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
    password: dnwjd123

jwt:
  secret-key: jfasdklfjlaskdfjlaksdfjfklasdjflkasdjfkldsajdfjaklsdfjkasdlfjflkasdfjlk
  expired-seconds: 600


server:
  port: 9091


---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update