spring:
  application:
    name: board-service
  profiles:
    include: common
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

jwt:
  secret-key: jfasdklfjlaskdfjlaksdfjfklasdjflkasdjfkldsajdfjaklsdfjkasdlfjflkasdfjlk
  expired-seconds: 600

server:
  port: 8082